name: 'ci'

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout x'
        uses: actions/checkout@v2
      - name: 'Set up python'
        uses: actions/setup-python@v2
        with:
            python-version: 3.9
      - name: 'Set up Poetry'
          uses:snok/install-poetry@v1
      - name: 'Install dependencies'
          run:poetry install --no-interaction --no-root
      - name: 'Run tests'
        run: poetry run pytest
      - name: 'Build project'
        run: poetry build
      - name: 'Publish project / Generate lib'
        run: poetry publish
